CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "vector";

CREATE SCHEMA IF NOT EXISTS users;
CREATE SCHEMA IF NOT EXISTS petitions;

GRANT ALL ON SCHEMA users TO ospetitions;
GRANT ALL ON SCHEMA petitions TO ospetitions;